/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pierce_ffmpeg_MPlayer */

#ifndef _Included_com_pierce_ffmpeg_MPlayer
#define _Included_com_pierce_ffmpeg_MPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pierce_ffmpeg_MPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_pierce_ffmpeg_MPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_pierce_ffmpeg_MPlayer
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pierce_ffmpeg_MPlayer_sound
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pierce_ffmpeg_MPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_pierce_ffmpeg_MPlayer_play
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
